### ISSUE TITLE
Can't test, dependency not found

### ISSUE THREAD

**Issue by Thomasdezeeuw** [justinas/alice#12]
https://github.com/stretch/testify/assert returns 404 but is required in testing, so I can't run the tests.

**Comment by justinas** [comment]
It's spelled "stretch**r**". Try `go get -t github.com/justinas/alice`. The `-t` flag makes the go tool also download test-only dependencies.

**Comment by Thomasdezeeuw** [comment]
Wow, great start to a new year. Sorry to bother you.

**Comment by justinas** [comment]
No problem at all. :)
