### ISSUE TITLE
How to deal with recovery middleware?

### ISSUE THREAD

**Issue by Rick1125** [justinas/alice#14]
You said Alice make no garentees with middleware's behaviors, 
it will stop the chain when panic,
so how can I make recovery as a middleware?

**Comment by justinas** [comment]
The `net/http` server will recover from panics automatically (see [the relevant code](http://golang.org/src/net/http/server.go#L1126)).

However, if you'd like to roll out your own recovery middleware, it should kick in as early as possible in the request lifecycle. Ideally, it should be the first in the chain.
```go
alice.New(recoveryMiddleware, ...).Then(handler)
```
