### ISSUE TITLE
Why DefaultServeMux is selected as nil replacement in calls to Then?

### ISSUE THREAD

**Issue by Komosa** [justinas/alice#15]
Additional question: why not _do nothing handler_?, like:
```golang
http.HandlerFunc(func(http.ResponseWriter, *http.Request) {})
```

**Comment by justinas** [comment]
Hi,

This replicates the behavior seen in `net/http.Serve()` (or `ListenAndServe()`), which also substitutes `nil` with `DefaultServeMux`.

My other idea for handling `nil` was to panic, but this seemed like a less scary alternative and a nice shortcut for those using `DefaultServeMux`.

A do-nothing handler is, I think, a rare case and easy to spin-out yourself.
