### ISSUE TITLE
Reworking Constructor interface?

### ISSUE THREAD

**Issue by jkearse3** [justinas/alice#24]
Thoughts on an implementation along the lines of this? I'm not a very experienced programmer, so my opinions may be invalid.
```go
type Constructor interface {
        Construct(http.Handler) http.Handler
}

type ConstructorFunc func(http.Handler) http.Handler
func (c ConstructorFunc) Construct(h http.Handler) http.Handler {
        return c(h)
}
```

This allows a function with that signature to be casted with ConstructorFunc, 
trying to follow the same idiom as http.Handler and http.HandlerFunc.

Useful things like wrapping something and giving it a Construct method would be great.

```go
type AliceLogger struct {
    *log.Logger
}

func (l *AliceLogger) Construct(h http.Handler) http.Handler {
    return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
        l.Printf("Logging the %v request.", r.Method)
        h.ServeHTTP(w, r)
    })
}
```

Although this would be a breaking change, but would allow for easy addition of various kinds of middleware simply by writing a Construct method. Also I noticed that Then() would allow Alice to implement itself (although unnecessary) by changing Then() to Construct().

```go
logger := &log.Logger{log.New(os.Stdout, "TestLogger", 0)}
alice.New(logger).Construct(nil)
```

Also, if it's breaking, maybe rename it to Adapter, with a method of Adapt(), based on this talk by Mat Ryer:
https://youtu.be/tIm8UkSf6RA?t=26m56s

I also implemented this in a separate branch to test it out:
https://github.com/jkearse3/alice/tree/newinterface

Thoughts or corrections to anything I proposed?

**Comment by justinas** [comment]
I just tested and it seems this is already possible with [method expressions](https://golang.org/ref/spec#Method_expressions).

```go
type Logger struct {
}

func (l *Logger) Adapt(h http.Handler) http.Handler {
	return h
}

func main() {
	l := Logger{}
	_ = alice.New(l.Adapt)
}
```

**Comment by jkearse3** [comment]
Understood. Thanks for the clarification!
