### ISSUE TITLE
Is there a negative consequences to using alice in a route?

### ISSUE THREAD

**Issue by cswank** [justinas/alice#27]
This works:

`r.Get("/hello/{name}", alice.New(middleware.Junk).Then(http.HandlerFunc(HelloServer)))`
`chain := alice.New(middleware.Auth).Then(r)`
`http.ListenAndServe(":12345", chain)`

For specifying route specific middleware.  Is there any reason why I should not do this and also have middleware for the router?  It would be useful for route specific permissions (the use case I had in mind).

**Comment by josephspurrier** [comment]
Nope, there are no negative consequences, that's actually a great way to use it.

* middleware.auth will be called on every request
* middleware.junk will only be called on /hello/{name}

**Comment by justinas** [comment]
I'm assuming the question has been answered.
