### ISSUE TITLE
go get error

### ISSUE THREAD

**Issue by lth2015** [justinas/alice#38]
when I install throttled,  execute `go get` command:

`go get "github.com/throttled/throttled"`

here is an error:

`can't load package: package github.com/throttled/throttled: code in directory /Users/litanhua/GoglandProjects/cloudstorage/src/github.com/throttled/throttled expects import "gopkg.in/throttled/throttled.v2"`

thank you!

**Comment by justinas** [comment]
Hi,

As indicated by the error message, Throttled uses a different import path. See [their README](https://github.com/throttled/throttled#installation).

Although it is not an issue with Alice, I will take some time to update the example as it has been out of date for a while now.

**Comment by lth2015** [comment]
@justinas  thank you so much~

When I delete `// import "gopkg.in/throttled/throttled.v2/store/storetest"` in files: 
`doc.go store/deprecated.go，store/memstore/memstore.go store/redigostore/redigostore.go store/storetest/doc.go store/storetest/storetest.go` it works.

**Comment by lth2015** [comment]
Correct answer:

[](http://stackoverflow.com/questions/43629475/go-get-error-when-using-throttled-gopkg-in-throttled-throttled-v2-library)

**Comment by lth2015** [comment]
Correct answer:
[](http://stackoverflow.com/questions/43629475/go-get-error-when-using-throttled-gopkg-in-throttled-throttled-v2-library)

**Comment by lth2015** [comment]
Correct answer:

http://stackoverflow.com/questions/43629475/go-get-error-when-using-throttled-gopkg-in-throttled-throttled-v2-library
