### ISSUE TITLE
Gracefully handle errors

### ISSUE THREAD

**Issue by Tkanos** [justinas/alice#41]
I don't like the way there are no error management.
What do you think to change a little bit the code to handle errors.

something like : 
```go
type Constructor func(http.Handler) (http.Handler, error)
type ErrorHandler func(http.Handler, error) http.Handler //create a new type to handle errors on Then
```

And then on Method Then : 
```go
func (c Chain) Then(h http.Handler, eh ErrorHandler) http.Handler {
	if h == nil {
		h = http.DefaultServeMux
	}

	for i := range c.constructors {
		h, err := c.constructors[len(c.constructors)-1-i](h)
		if err != nil && eh != nil {
			h = eh(h, err)
                        break
		}
	}

	return h
}
```

nothing else change. But it will allow people to create middlewares like : 
```go
var ErrInvalidParameter = errors.New("invalid parameter")

func Mid1(h http.Handler) (http.Handler, error) {
     //Do a lot of stuff and if there are an issue with parameter 
    return h, ErrInvalidParameter // can be another error depending on the code of course this is just an example
}

func ErrHandler(http.Handler, error) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch err {
		        case ErrInvalidParameter:
			       w.WriteHeader(http.StatusBadRequest)
		        default:
			       w.WriteHeader(http.StatusInternalServerError)
		}
	        
               //Add more information if wanted
	        w.Header().Set("Content-Type", "application/json; charset=utf-8")
	        json.NewEncoder(w).Encode(map[string]interface{}{
		         "error": err.Error(),
                }
           })
}

//And somewhere on main.go
alice.New(Mid1, Mid2, Mid3).Then(App, ErrHandler)

```

What do you think ?
If you agree with the concept, I can do the code and unit tests.

**Comment by Tkanos** [comment]
doing that we don't keep the backward compatibility, because constructor is changed.
But if you want to keep Alice as simple as it is.
This catched version can be a Tag of Alice on github.

Or if you have ideas to keep the backward compatibility ?

**Comment by justinas** [comment]
Hey @Tkanos,

Thanks for your suggestion, but as I do not see this working without breaking backwards compatibility, I do not think this implementation currently has place in Alice. The whole idea is to keep a completely standard `http.Handler` interface which, sadly, does not have a standard way to indicate error. The closest way to having it in the standard interface would be, if anything, signaling an error on `request.Context`. 

There might be some frameworks have this signature with an `error` return, so these could be considered as alternatives to alice in this case.

Thanks again!

**Comment by Tkanos** [comment]
I fully understand. And you are right.

Thanks.
