### ISSUE TITLE
Initialize Go Modules and Tag v1.0.0 release

### ISSUE THREAD

**Issue by gilcrest** [justinas/alice#48]
I realize alice had a v1.0.0 release which was removed. Now that modules support for Go is stable and adoption is growing, would it be possible to add back the v1.0.0 release tag and initialize modules for alice? Thanks for your consideration!

Dan

**Comment by euskadi31** [comment]
ping @justinas

**Comment by justinas** [comment]
Thanks for the ping. Are we possibly better off tagging it `v2.0.0` in order not to break any configurations that might still rely on the now-deleted `v1.0.0` tag?

**Comment by justinas** [comment]
> Note that if you are adopting modules for the first time for a pre-existing repository or set of packages that have already been tagged v2.0.0 or higher before adopting modules, then the recommended best practice is to increment the major version when first adopting modules. For example, if you are the author of foo, and the latest tag for the foo repository is v2.2.2, and foo has not yet adopted modules, then the best practice would be to use v3.0.0 for the first release of foo to adopt modules 

https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher

**Comment by euskadi31** [comment]
ok, v1 without go module and v2 with go module ?

**Comment by justinas** [comment]
On the other hand:

> Why are major versions v0, v1 omitted from import paths?
>
>v1 is omitted from import paths for two reasons. First, many developers will create packages that never make a breaking change once they reach v1, which is something we've encouraged from the start. We don't believe all those developers should be forced to have an explicit v1 when they may have no intention of ever releasing v2. The v1 becomes just noise.
>
> https://github.com/golang/go/issues/24301#issuecomment-371228664

Alice is certainly one of these projects that aims to "never make a breaking change" / "[has] no intention of ever releasing v2". Maybe we could get away with `v1.1.0` for the current master and `v1.2.0` after adding a `go.mod`.

**Comment by euskadi31** [comment]
indeed

**Comment by gilcrest** [comment]
"Alice is certainly one of these projects that aims to "never make a breaking change" / "[has] no intention of ever releasing v2". Maybe we could get away with v1.1.0 for the current master and v1.2.0 after adding a go.mod" - I think this is a great solution and wholly appropriate. I definitely don't think you need a v2 as there's been no breaking changes!

**Comment by euskadi31** [comment]
Thanks You @justinas ❤️

**Comment by gilcrest** [comment]
Woohoo!  Thanks @justinas !
